name: Remote BuildKit Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v3
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsBuildKitRole
        aws-region: us-east-2
    - uses: docker/setup-buildx-action@v2
      with:
        driver: remote
        endpoint: tcp://${{ secrets.BUILDKIT_HOST }}:9999
    - uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: test-image:latest
        load: true
